// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5F1P6XjwSMzb3fd3cgPp69los8R8rKbc',
    appId: '1:607639301039:web:f8d70ac90a8b7e94a45d5a',
    messagingSenderId: '607639301039',
    projectId: 'swacch-kabadi',
    authDomain: 'swacch-kabadi.firebaseapp.com',
    storageBucket: 'swacch-kabadi.appspot.com',
    measurementId: 'G-L4HGZPWNPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5axotXXu_ja1hgX2rdIZIWfQcUFmSvak',
    appId: '1:607639301039:android:f79c821427a93fb4a45d5a',
    messagingSenderId: '607639301039',
    projectId: 'swacch-kabadi',
    storageBucket: 'swacch-kabadi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPdckHJQXIhgF5JlJWJQKP9YP6PESyt0Q',
    appId: '1:607639301039:ios:e455024a12b917a9a45d5a',
    messagingSenderId: '607639301039',
    projectId: 'swacch-kabadi',
    storageBucket: 'swacch-kabadi.appspot.com',
    androidClientId: '607639301039-17qtae8q7l0t2tfehn90g0kmh294pvav.apps.googleusercontent.com',
    iosClientId: '607639301039-vg6tkmkt6lh49m8dr5tmisj8fd29uiuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.kabadmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPdckHJQXIhgF5JlJWJQKP9YP6PESyt0Q',
    appId: '1:607639301039:ios:7bae310997b563aba45d5a',
    messagingSenderId: '607639301039',
    projectId: 'swacch-kabadi',
    storageBucket: 'swacch-kabadi.appspot.com',
    androidClientId: '607639301039-17qtae8q7l0t2tfehn90g0kmh294pvav.apps.googleusercontent.com',
    iosClientId: '607639301039-fndt90hj3suatsj19tbcikc0vhjkhrol.apps.googleusercontent.com',
    iosBundleId: 'com.example.kabadmanager.RunnerTests',
  );
}
